export const bauDeItens = {
  paramecia: [
    {
      nome: "Ami Ami no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário criar redes extremamente resistentes de qualquer parte do corpo.",
    },
    {
      nome: "Ato Ato no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma pessoas e objetos em obras de arte vivas, ainda que limitadas.",
    },
    {
      nome: "Awa Awa no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Produz bolhas de sabão que limpam e deixam o alvo escorregadio, reduzindo a defesa.",
    },
    {
      nome: "Baku Baku no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede ao usuário uma boca capaz de devorar qualquer coisa e combinar materiais ingeridos.",
    },
    {
      nome: "Bane Bane no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma as pernas em molas, permitindo saltos e ataques elásticos.",
    },
    {
      nome: "Bara Bara no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite dividir o corpo em pedaços e controlá-los independentemente.",
    },
    {
      nome: "Bari Bari no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Cria barreiras invisíveis e quase impenetráveis para defesa.",
    },
    {
      nome: "Bata Bata no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar e controlar manteiga viscosa para imobilizar oponentes.",
    },
    {
      nome: "Beri Beri no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma partes do corpo em esferas que podem se separar e se recombinar.",
    },
    {
      nome: "Beta Beta no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite cobrir o corpo com um muco pegajoso que adere e controla objetos ao redor.",
    },
    {
      nome: "Bisu Bisu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Produz e manipula biscoitos, criando estruturas e soldados de biscoito.",
    },
    {
      nome: "Bomu Bomu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Faz o corpo do usuário explodir como bomba sem sofrer dano.",
    },
    {
      nome: "Buku Buku no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá o poder de controlar livros, voar sobre eles e aprisionar seres dentro de livros.",
    },
    {
      nome: "Buki Buki no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar partes do corpo em diversas armas, como espadas e canhões.",
    },
    {
      nome: "Chiyu Chiyu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar uma água de cura capaz de recuperar feridas rapidamente.",
    },
    {
      nome: "Choki Choki no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma as mãos em tesouras que cortam praticamente qualquer coisa.",
    },
    {
      nome: "Deka Deka no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário aumentar drasticamente o tamanho de seu corpo.",
    },
    {
      nome: "Doku Doku no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede o controle e produção de venenos altamente letais.",
    },
    {
      nome: "Doa Doa no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Cria portas em qualquer superfície, inclusive no ar, permitindo teleporte.",
    },
    {
      nome: "Doru Doru no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Produz cera que endurece como aço para moldar armas e armaduras.",
    },
    {
      nome: "Fude Fude no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite dar vida a desenhos, materializando-os no mundo real.",
    },
    {
      nome: "Fuwa Fuwa no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá ao usuário o poder de levitar objetos e a si mesmo, controlando a gravidade local.",
    },
    {
      nome: "Gasha Gasha no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite desmantelar e reconstruir objetos mecânicos de maneira criativa.",
    },
    {
      nome: "Gomu Gomu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o corpo em borracha elástica, imunizando contra impactos contundentes.",
    },
    {
      nome: "Gura Gura no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Cria terremotos e ondas de choque capazes de destruir terra e mar.",
    },
    {
      nome: "Guru Guru no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede a habilidade de girar partes do corpo rapidamente como hélices.",
    },
    {
      nome: "Hana Hana no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite fazer brotar cópias de partes do corpo em qualquer superfície.",
    },
    {
      nome: "Hira Hira no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transmuta objetos em matéria flexível que ondula como papel ou tecido.",
    },
    {
      nome: "Hobi Hobi no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma qualquer pessoa tocada em brinquedo e impede que se lembrem dela; o usuário deixa de envelhecer.",
    },
    {
      nome: "Horo Horo no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar fantasmas que podem explodir ou induzir sentimentos negativos extremos.",
    },
    {
      nome: "Horu Horu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá controle total sobre hormônios do corpo, alterando aparência, gênero ou força.",
    },
    {
      nome: "Ishi Ishi no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite fundir-se com rocha e controlar estruturas pétreas.",
    },
    {
      nome: "Ito Ito no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar e manipular fios afiados, controlar pessoas como marionetes e cortar quase tudo.",
    },
    {
      nome: "Jake Jake no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o usuário em uma jaqueta que, quando vestida por alguém, controla o corpo do hospedeiro.",
    },
    {
      nome: "Jiki Jiki no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede magnetismo, permitindo atrair e repulsar objetos metálicos gigantescos.",
    },
    {
      nome: "Kage Kage no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá ao usuário domínio sobre sombras, podendo roubá-las e animar cadáveres.",
    },
    {
      nome: "Kilo Kilo no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite alterar o próprio peso de 1 até 10 000 quilos sem mudar o tamanho.",
    },
    {
      nome: "Mane Mane no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite copiar a aparência física de qualquer pessoa tocada no rosto.",
    },
    {
      nome: "Mato Mato no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá ao usuário a capacidade de marcar alvos e lançar projéteis que sempre os encontram.",
    },
    {
      nome: "Mero Mero no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma em pedra qualquer um dominado pela luxúria ou adoração pelo usuário.",
    },
    {
      nome: "Mochi Mochi no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite produzir e transformar-se em mochi, uma massa pegajosa e versátil.",
    },
    {
      nome: "Nikyu Nikyu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede almofadas nas mãos que repelem tudo o que tocam, inclusive dor e ar.",
    },
    {
      nome: "Noro Noro no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Emite raios que reduzem drasticamente a velocidade do alvo por alguns segundos.",
    },
    {
      nome: "Nui Nui no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite costurar qualquer coisa, inclusive seres vivos e objetos, unindo-os permanentemente.",
    },
    {
      nome: "Ope Ope no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Cria um espaço esférico onde o usuário pode manipular matéria e vida como um cirurgião onipotente.",
    },
    {
      nome: "Ori Ori no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite gerar grades de ferro para prender pessoas ou objetos instantaneamente.",
    },
    {
      nome: "Pamu Pamu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Faz objetos inflarem e explodirem como se fossem balões sobrecarregados.",
    },
    {
      nome: "Sabi Sabi no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Provoca ferrugem instantânea ao tocar metal, deteriorando armamentos.",
    },
    {
      nome: "Shari Shari no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma partes do corpo em rodas afiadas que giram para atacar.",
    },
    {
      nome: "Soru Soru no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite interagir e manipular almas, extraindo tempo de vida ou animando objetos inanimados.",
    },
    {
      nome: "Sube Sube no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Alisa a pele do usuário tornando-a lisa como óleo, fazendo ataques escorregarem e o usuário ficar belo.",
    },
    {
      nome: "Sui Sui no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite nadar através de superfícies sólidas como se fossem água.",
    },
    {
      nome: "Suke Suke no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede invisibilidade ao usuário e ao que ele toca.",
    },
    {
      nome: "Supa Supa no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o corpo em aço e gera lâminas afiadas em qualquer parte.",
    },
    {
      nome: "Toge Toge no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite fazer brotar espinhos por todo o corpo para atacar ou defender.",
    },
    {
      nome: "Ton Ton no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite alterar o peso do usuário para múltiplos de toneladas, aumentando a força de impacto.",
    },
    {
      nome: "Woshu Woshu no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Lava e “estende” pessoas como roupas, removendo suas maldades temporariamente.",
    },
    {
      nome: "Yomi Yomi no Mi",
      tipo: "Paramecia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede uma segunda vida ao usuário e poder sobre a alma após a morte.",
    },
  ],
  logia: [
    {
      nome: "Ame Ame no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se e manipular melaço ou xarope doce, tornando o usuário viscoso.",
    },
    {
      nome: "Pasa Pasa no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá poder de criar e controlar papel e dividir o corpo em folhas de papel.",
    },
    {
      nome: "Gasu Gasu no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em gás e controlar diferentes tipos de gases, incluindo venenosos.",
    },
    {
      nome: "Goro Goro no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede ao usuário o poder de criar, controlar e transformar-se em eletricidade.",
    },
    {
      nome: "Hie Hie no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite congelar instantaneamente o ambiente e transformar o corpo em gelo sólido.",
    },
    {
      nome: "Magu Magu no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Dá o poder de gerar, controlar e tornar-se magma, queimando quase tudo.",
    },
    {
      nome: "Mera Mera no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite produzir, controlar e tornar-se fogo, emitindo chamas intensas.",
    },
    {
      nome: "Moku Moku no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o corpo em fumaça e permite manipular nuvens de fumaça de várias densidades.",
    },
    {
      nome: "Mori Mori no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede controle absoluto sobre plantas e vegetação, gerando florestas e vinhas.",
    },
    {
      nome: "Numa Numa no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o usuário em lama de pântano que pode absorver pessoas e objetos.",
    },
    {
      nome: "Pika Pika no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em luz, mover-se à velocidade da luz e disparar feixes luminosos.",
    },
    {
      nome: "Suna Suna no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar, controlar e transformar-se em areia, drenando umidade para endurecer.",
    },
    {
      nome: "Susu Susu no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar e controlar fuligem, tornando o corpo em pó negro e formando construtos.",
    },
    {
      nome: "Toro Toro no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede a habilidade de transformar-se em um líquido transparente e expandir seu volume.",
    },
    {
      nome: "Yami Yami no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite manipular a escuridão com gravidade, absorvendo ataques e neutralizando poderes de outras frutas.",
    },
    {
      nome: "Yuki Yuki no Mi",
      tipo: "Logia",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite criar, controlar e transformar-se em neve, formando barreiras geladas.",
    },
  ],
  zoan: [
    {
      nome: "Hito Hito no Mi",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma um animal em humano ou concede forma humana com inteligência superior a quem a consome.",
    },
    {
      nome: "Inu Inu no Mi [Dachshund]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um cão da raça dachshund ou híbrido.",
    },
    {
      nome: "Inu Inu no Mi [Lobo]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em lobo completo ou forma híbrida.",
    },
    {
      nome: "Inu Inu no Mi [Chacal]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em chacal, ganhando sentidos e velocidade aprimorados.",
    },
    {
      nome: "Neko Neko no Mi [Leopardo]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em leopardo ou forma híbrida, aumentando força e agilidade.",
    },
    {
      nome: "Ushi Ushi no Mi [Bisonte]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em bisonte ou híbrido, ampliando força física.",
    },
    {
      nome: "Ushi Ushi no Mi [Girafa]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em girafa, estendendo pescoço e membros para ataques de longo alcance.",
    },
    {
      nome: "Uma Uma no Mi",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em cavalo ou forma híbrida veloz.",
    },
    {
      nome: "Zou Zou no Mi",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em elefante, conferindo grande massa e poder de destruição.",
    },
    {
      nome: "Mogu Mogu no Mi",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em toupeira, permitindo cavar e mover-se subterraneamente.",
    },
    {
      nome: "Hebi Hebi no Mi [Cobra-Rei]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em uma cobra-rei, venenosa e flexível.",
    },
    {
      nome: "Hebi Hebi no Mi [Anaconda]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em anaconda, aumentando força constritiva.",
    },
    {
      nome: "Tori Tori no Mi [Falcão]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em falcão, obtendo voo e visão aguçada.",
    },
    {
      nome: "Tori Tori no Mi [Albatroz]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em albatroz, garantindo longos voos e resistência.",
    },
    {
      nome: "Mushi Mushi no Mi [Abelha]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em uma abelha gigante, capaz de voar e usar ferrão venenoso.",
    },
    {
      nome: "Mushi Mushi no Mi [Besouro-Rinoceronte]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em besouro-rinoceronte, com casco duro e capacidade de voo.",
    },
    {
      nome: "Sara Sara no Mi [Axolote]",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um axolote, capaz de regenerar membros e nadar agilmente.",
    },
    {
      nome: "Zo Zo no Mi",
      tipo: "Zoan",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário transformar-se em elefante pequeno conhecido por orar, alterando força e tamanho.",
    },
    {
      nome: "Hito Hito no Mi [Daibutsu]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o usuário em um grande Buda dourado capaz de emitir ondas de choque místicas.",
    },
    {
      nome: "Hito Hito no Mi [Nika]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário tornar-se o deus do sol Nika, adquirindo poderes elásticos e liberdade absoluta.",
    },
    {
      nome: "Hebi Hebi no Mi [Yamata no Orochi]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Transforma o usuário em uma serpente de oito cabeças da mitologia japonesa.",
    },
    {
      nome: "Inu Inu no Mi [Kyubi no Kitsune]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário transformar-se em uma raposa de nove caudas, capaz de mudar de aparência e criar ilusões.",
    },
    {
      nome: "Inu Inu no Mi [Okuchi no Makami]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário tornar-se um lobo divino protetor com capacidade de gerar gelo.",
    },
    {
      nome: "Tori Tori no Mi [Fênix]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em uma fênix de chamas azuis que curam ferimentos e concedem voo.",
    },
    {
      nome: "Uo Uo no Mi [Dragão Azul (Seiryu)]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Concede a capacidade de transformar-se em um dragão azul colossal, disparando rajadas elementares.",
    },
    {
      nome: "Uma Uma no Mi [Pégaso]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um cavalo alado lendário, garantindo voo rápido e resistência.",
    },
    {
      nome: "Batto Batto no Mi [Vampiro]",
      tipo: "Zoan Mítica",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário tornar-se um vampiro mítico, sugando energia vital e transformando-se em morcego.",
    },
    {
      nome: "Ryu Ryu no Mi [Alossauro]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um alossauro, aumentando força física e ferocidade.",
    },
    {
      nome: "Ryu Ryu no Mi [Braquiossauro]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um braquiossauro gigante com pescoço longo e resistência esmagadora.",
    },
    {
      nome: "Ryu Ryu no Mi [Pteranodonte]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um pteranodonte, conferindo voo e garras afiadas.",
    },
    {
      nome: "Ryu Ryu no Mi [Paquicefalossauro]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite ao usuário transformar-se em um paquicefalossauro com cabeçada devastadora.",
    },
    {
      nome: "Ryu Ryu no Mi [Tricerátops]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um tricerátops, usando chifres para ataques poderosos.",
    },
    {
      nome: "Neko Neko no Mi [Tigre-dente-de-sabre]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um tigre dente-de-sabre, aumentando velocidade e mordida.",
    },
    {
      nome: "Zou Zou no Mi [Mamute]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em um mamute gigantesco, com tromba poderosa e força bruta.",
    },
    {
      nome: "Kumo Kumo no Mi [Rosamygale Grauvogeli]",
      tipo: "Zoan Ancestral",
      img: "./imagens/gomu-gomu.webp",
      desc: "Permite transformar-se em uma aranha pré-histórica, lançando teias resistentes.",
    },
  ],
};
